import { test, expect } from 'vitest'
import { isUrl } from '../src/index'

const tests = {
  // These URLs are valid
  'http://foo.com/blah_blah': true,
  'https://foo.com/blah_blah': true,
  'https://foo.com/blah_blah/': true,
  'https://foo.com/blah_blah_(wikipedia)': true,
  'https://foo.com/blah_blah_(wikipedia)_(again)': true,
  'https://www.example.com/wpstyle/?p=364': true,
  'https://www.example.com/foo/?bar=baz&inga=42&quux': true,
  'https://userid:password@example.com:8080': true,
  'https://userid:password@example.com:8080/': true,
  'https://userid@example.com': true,
  'https://userid@example.com/': true,
  'https://userid@example.com:8080': true,
  'https://userid@example.com:8080/': true,
  'https://userid:password@example.com': true,
  'https://userid:password@example.com/': true,
  'https://142.42.1.1/': true,
  'https://142.42.1.1:8080/': true,
  'https://foo.com/blah_(wikipedia)#cite-1': true,
  'https://foo.com/blah_(wikipedia)_blah#cite-1': true,
  'https://foo.com/unicode_(✪)_in_parens': true,
  'https://foo.com/(something)?after=parens': true,
  'https://code.google.com/events/#&product=browser': true,
  'https://j.mp': true,
  'ftp://foo.bar/baz': true,
  'https://foo.bar/?q=Test%20URL-encoded%20stuff': true,
  "https://-.~_!$&'()*+,;=:%40:80%2f::::::@foo.com": true,
  'https://1337.net': true,
  'https://a.b-c.de': true,
  'https://223.255.255.254': true,
  'https://foo_bar.example.com/': true,
  'https://google.com//': true,
  'https://google.com/asd//': true,
  // Special characters URL are also valid
  'https://foo.com/ギットハブ': true,
  'https://ギットハブ.com': true,
  'https://✪df.ws/123': true,
  'https://➡.ws/䨹': true,
  'https://⌘.ws': true,
  'https://⌘.ws/': true,
  'https://☺.damowmow.com/': true,
  'https://مثال.إختبار': true,
  'https://例子.测试': true,
  'https://उदाहरण.परीक्षा': true,
  // These URLs currently pass, but we're not sure if they're valid
  'https://www.google.com/"asdf"': true,
  'https://a.b--c.de/': true,
  'https://www.foo.bar./': true,
  // These URLs should fail
  'mailto:me@github.com': false,
  'http://': false,
  'https://.': false,
  'https://..': false,
  'https://../': false,
  'https://?': false,
  'https://??': false,
  'https://??/': false,
  'https://#': false,
  'https://##': false,
  'https://##/': false,
  'https://foo.bar?q=Spaces should be encoded': false,
  '//': false,
  '//a': false,
  '///a': false,
  '///': false,
  'https:///a': false,
  'foo.com': false,
  'rdar://1234': false,
  'h://test': false,
  'https:// shouldfail.com': false,
  ':// should fail': false,
  'https://foo.bar/foo(bar)baz quux': false,
  'ftps://foo.bar/': false,
  'https://-error-.invalid/': false,
  'https://-a.b.co': false,
  'https://a.b-.co': false,
  'https://0.0.0': false,
  'https://10.1.1': false,
  'https://10.1.1.255': false,
  'https://224.1.1.1': false,
  'https://1.1.1.1.1': false,
  'https://123.123.123': false,
  'https://3628126748': false,
  'https://.www.foo.bar/': false,
  'https://.www.foo.bar./': false,
  'https://10.1.1.1': false,
  'https://10.1.1.254': false,
}

Object.entries(tests).forEach(([url, expected]) => {
  test(url, () => expect(isUrl(url)).toEqual(expected))
})
